
[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "teraflops"
authors = [
  {name = "Aaron Andersen", email = "aaron@fosslib.net"}
]
description = "teraflops - a terraform ops tool which is sure to be a flop"
version = "0.1.1"
readme = "README.md"
license = {text = "MIT"}
dependencies = [
  "rich"
]

[project.scripts]
teraflops = "teraflops.main:run"

[tool.setuptools.packages.find]
include = ["teraflops"]
