
[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "teraflops"
authors = [
  {name = "Aaron Andersen", email = "aaron@fosslib.net"}
]
description = "teraflops - a terraform ops tool which is sure to be a flop"
version = "0.1.1"
readme = "README.md"
license = "MIT"
dependencies = [
  "rich"
]

[project.scripts]
teraflops = "teraflops.main:run"

[tool.setuptools.packages.find]
include = ["teraflops", "teraflops.*"]

[tool.setuptools_scm]

[tool.ruff]
line-length = 120

[tool.ruff.format]
quote-style = "single"

[tool.ruff.lint]
select = [
  "E",      # pycodestyle errors
  "W",      # pycodestyle warnings
  "F",      # pyflakes
  "I",      # isort
  "B",      # flake8-bugbear
  "C4",     # flake8-comprehensions
  "UP",     # pyupgrade
]
